[package]
name = "card_game_app"
version = "0.1.0"
authors = ["NilsHasNoGithub <niolopa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
card_game_server = { path = "../card_game_server"}